---
title: "New York NOAA Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Site Homepage", href: "index.html", align: left }
---

```{r setup, include=FALSE}
# load packages
library(flexdashboard)
library(tidyverse)
library(leaflet)
library(plotly)
library(p8105.datasets)

# default figure options
knitr::opts_chunk$set(
  fig.width = 6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d


```

```{r tidy data}
# Pull NY eather station data
data("ny_noaa")

# Pull lat and long coords for NY weather station
#df_ghcnd = read_csv("files/ghcnd-stations_NY.csv") |>  # if website link goes down
df_ghcnd = read_csv("https://www.atmos.albany.edu/facstaff/timm/ATM315spring14/R/data/NY/ghcnd-stations_NY.csv") |> 
  janitor::clean_names() |> 
  rename(city = info1) |> 
  mutate(city = str_to_title(city),
         city = case_when(city == "New" ~ "New York City",
                          city != "New" ~ city))
# Restrict to ids in the NOAA data set
df_noaa = left_join(ny_noaa, df_ghcnd) |> 
  mutate(tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) |> 
  separate(date, into = c("year", "month", "day"), "-") |> 
  mutate(year = as.numeric(year),
         month = as.numeric(month))
```

Column {data-width=500}
-----------------------------------------------------------------------

### Average annual precipitation over NY state

```{r chart a}
# summarize data
df_prcp = df_noaa |> 
  drop_na(prcp, lat, lon) |> 
  group_by(id) |> 
  summarize(avg_prcp = mean(prcp),
            lat = mean(lat),
            long = mean(lon)
            ) |> 
  filter(avg_prcp < 100)

# define color gradient by prcp
pal <- colorNumeric(
  palette = "viridis",
  domain = df_prcp$avg_prcp)

# generate plot
df_prcp |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(~long, ~lat, label = ~id,
                   color = ~pal(avg_prcp),
                   radius = 2) |> 
  addLegend(position = "topright",
            pal = pal, values = df_prcp$avg_prcp,
            title = "Precipitation [mm]")
```


### Comparing rainfall to distance from NYC

```{r chart b}
df_nyc_dist = df_noaa |> 
  drop_na() |> 
  group_by(id, city) |> 
  summarize(avg_rain = mean(prcp),
            avg_snow = mean(snow),
            avg_tmax = mean(tmax),
            long = mean(lon),
            lat = mean(lat)) |> 
  mutate(dist_nyc = pracma::haversine(c(lat,long),c(40.7128,-74.0060))) |> 
  ungroup()
# the haversine function gives the distance bwn two lat,long pairs

fit <-  lm(avg_rain ~ dist_nyc, data = df_nyc_dist) |> fitted.values()

df_nyc_dist |>   
  plot_ly(x = ~dist_nyc, y = ~avg_rain) |> 
  add_markers(y = ~avg_rain, text = ~city, 
              hovertemplate = "%{text}<extra></extra>") |> 
  add_lines(x = ~dist_nyc, y = fit, mode = "lines",
            hovertemplate = "<extra></extra>") |> 
  layout(showlegend = FALSE, 
         xaxis = list(title = "Distance from NYC (km)"), 
         yaxis = list(title = "Average Daily Rainfall (tenths mm)")
         )



```


Column {.tabset data-width=500}
-----------------------------------------------------------------------
### Annual Temperature

```{r chart c}
df_noaa |> 
  filter(id %in% c("USW00094725", 
                   "USW00014735",
                   "USW00094728",
                   "USW00014733")) |> 
  drop_na(tmax) |> 
  group_by(city, year) |> 
  summarize(max_temp = mean(tmax)) |> 
  plot_ly(x = ~year, y = ~max_temp, color = ~city,
          type = "scatter", mode = "lines", colors = "viridis") |> 
  layout(legend = list(orientation = "h", y = 1.05),
         xaxis = list(title = "Year"),
         yaxis = list(title = "Average temperature (°C)"))
```

### Daily Temperature

```{r chart d}
df_noaa |> 
  drop_na(tmax) |> 
  filter(id %in% c("USW00094725", 
                   "USW00014735",
                   "USW00094728",
                   "USW00014733")) |> 
  mutate(season = case_when(
    month %in% c(3, 4, 5) ~ "Spring", 
    month %in% c(6, 7, 8) ~ "Summer", 
    month %in% c(9, 10, 11) ~ "Fall", 
    month %in% c(12, 1, 2) ~ "Winter"),
    season = fct_relevel(season, c("Spring", "Summer", "Fall", "Winter"))) |> 
  #filter(season == "Summer" | season == "Winter") |> 
  plot_ly(x = ~city, y = ~tmax, color = ~season,
          type = "box", colors = "viridis") |> 
  layout(legend = list(title = list(text = "<b>  Season</b>")),
         boxmode = "group",
         xaxis = list(title = ""),
         yaxis = list(title = "Daily Temperature (°C)"))
```
