---
title: "make plots"
author: "Derek Lamb"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(leaflet)
library(plotly)
library(p8105.datasets)


knitr::opts_chunk$set(
  fig.width = 6,
  out.width = "90%"
)

## These are options that i'm going to treat as default for now
## I don't love viridis, but don't have a better option yet
theme_set(theme_bw() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r data}
# Pull NY eather station data
data("ny_noaa")

# Pull lat and long coords for NY weather station
df_ghcnd = read_csv("https://www.atmos.albany.edu/facstaff/timm/ATM315spring14/R/data/NY/ghcnd-stations_NY.csv") |> 
  janitor::clean_names() |> 
  rename(city = info1) |> 
  mutate(city = str_to_title(city),
         city = case_when(city == "New" ~ "New York City",
                          city != "New" ~ city))

# Restrict to ids in the NOAA data set
df_noaa = left_join(ny_noaa, df_ghcnd) |> 
  mutate(tmax = as.numeric(tmax)/10,
         tmin = as.numeric(tmin)/10) |> 
  separate(date, into = c("year", "month", "day"), "-") |> 
  mutate(year = as.numeric(year),
         month = as.numeric(month))
```

```{r 4 city boxplot}
df_noaa |> 
  filter(id %in% c("USW00094725", 
                   "USW00014735",
                   "USW00094728",
                   "USW00014733")) |> 
  filter(snow > 0) |> 
  plot_ly(x = ~city, y = ~snow, 
          type = "box")
```

```{r precip plot}
df_noaa |> 
  drop_na(prcp, snow, tmax) |> 
  group_by(id, city) |> 
  summarize(avg_rain = mean(prcp),
            avg_snow = mean(snow),
            avg_tmax = mean(tmax)) |> 
  plot_ly(x = ~avg_rain, y = ~avg_snow, color = ~avg_tmax,
          type = "scatter", mode = "markers",
          text = ~city, colors = "viridis")
```

```{r}
df_noaa |> 
  filter(id %in% c("USW00094725", 
                   "USW00014735",
                   "USW00094728",
                   "USW00014733")) |> 
  drop_na(tmax) |> 
  group_by(city, year) |> 
  summarize(max_temp = max(tmax)) |> 
  plot_ly(x = ~year, y = ~max_temp, color = ~city,
          type = "scatter", mode = "lines", colors = "viridis")
```

```{r precip geography}
# summarize data
df_prcp = df_noaa |> 
  drop_na(prcp, lat, lon) |> 
  group_by(id) |> 
  summarize(avg_prcp = mean(prcp),
            lat = mean(lat),
            long = mean(lon)
            ) |> 
  filter(avg_prcp < 100)

# define color gradient by prcp
pal <- colorNumeric(
  palette = "viridis",
  domain = df_prcp$avg_prcp)

# generate plot
df_prcp |> 
  leaflet() |> 
  addProviderTiles(providers$CartoDB.Positron) |> 
  addCircleMarkers(~long, ~lat, label = ~id,
                   color = ~pal(avg_prcp),
                   radius = 2) |> 
  addLegend(position = "topright",
            pal = pal, values = df_prcp$avg_prcp,
            title = "Precipitation [mm]")
```


